### ISSUE TITLE
how can i run this image in MacOS?

### ISSUE THREAD

**Issue by amdgigabyte** [csicar/dockerwm#1]
` -v /tmp/.X11-unix:/tmp/.X11-unix` this folder does not exist in MacOS

**Comment by csicar** [comment]
No, is does not work on MacOS out of the box, because MacOS does not run a X Server.

I think there is a way to start an X-Server on MacOS and pass the socket to the docker image, but unfortunately I don't know how and have no way to test it

**Comment by amdgigabyte** [comment]
Thanks a lot! Still a very good try!
